[package]
name = "timeout"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime = "2.1.0"
libc = "0.2.97"
nix = "0.24.1"
parse_duration = "2.1.1"
structopt = "0.3.26"
